# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: HomeAssistant DataDog Agent Addon
version: "1.4.0"
slug: dd-agent-ha-addon
description: HomeAssistant DataDog Agent Addon
url: "https://github.com/machinehead/dd-agent-ha-addon/tree/main/example"
arch:
  - aarch64
  - amd64
init: false
map:
  - share:rw
options:
  - DD_API_KEY: ""
schema:
  DD_API_KEY: "str"
image: "ghcr.io/machinehead/{arch}-dd-agent-ha-addon"
